name: Auto Update Minecraft Manifest

on:
  schedule:
    - cron: '0 */12 * * *' # On passe à 12h pour laisser respirer le serveur face à la tonne de fichiers
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4

    - name: Installer Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Optimiser les paramètres Git pour les gros volumes de fichiers
      run: |
        git config --global core.preloadindex true
        git config --global core.fscache true
        git config --global merge.renameLimit 4000

    - name: Compiler et exécuter le script Java
      run: |
        javac parser/ManifestParser.java
        java -cp parser ManifestParser

    - name: Pousser la structure sur GitHub
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # On force Git à tout prendre en compte calmement
        git add myfiles/
        
        # On vérifie s'il y a de nouveaux fichiers avant de commit
        if ! git diff-index --quiet HEAD; then
          git commit -m "🤖 Auto-update: Synchronisation complète des dossiers de téléchargement Mojang"
          git push
        else
          echo "Aucun changement détecté, pas besoin de mettre à jour."
        fiindex --quiet HEAD || git commit -m "🤖 Auto-update: Nouvelle version Minecraft détectée"
        git push
