name: Auto Update Minecraft Manifest

on:
  schedule:
    # S'exécute automatiquement toutes les 12 heures pour laisser respirer les requêtes
    - cron: '0 */12 * * *'
  workflow_dispatch: # Te permet de forcer la mise à jour manuellement via l'onglet Actions

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4

    - name: Installer Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Optimiser les paramètres Git pour les gros volumes de fichiers
      run: |
        git config --global core.preloadindex true
        git config --global core.fscache true
        git config --global merge.renameLimit 4000

    - name: Compiler et exécuter le script Java
      run: |
        # 1. On crée un dossier temporaire pour la compilation
        mkdir -p bin
        
        # 2. On compile les classes dedans (-d bin)
        javac -d bin parser/ManifestParser.java
        
        # 3. On l'exécute depuis le dossier bin (-cp bin)
        java -cp bin parser.ManifestParser

    - name: Pousser la structure sur GitHub
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Ajoute l'arborescence générée par le script Java (le dossier bin est ignoré)
        git add myfiles/
        
        # Le commit ne se fait que si Mojang a sorti une nouvelle version
        if ! git diff-index --quiet HEAD; then
          git commit -m "🤖 Auto-update: Synchronisation complète des dossiers de téléchargement Mojang"
          git push
        else
          echo "Aucune modification détectée dans le manifeste de Mojang. Le site est déjà à jour."
        fi
