name: Auto Update Minecraft Manifest

on:
  schedule:
    # S'exécute automatiquement toutes les 12 heures pour laisser respirer les requêtes
    - cron: '0 */12 * * *'
  workflow_dispatch: # Te permet de forcer la mise à jour manuellement via l'onglet Actions

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4

    - name: Installer Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Optimiser les paramètres Git pour les gros volumes de fichiers
      run: |
        git config --global core.preloadindex true
        git config --global core.fscache true
        git config --global merge.renameLimit 4000

    - name: Compiler et exécuter le script Java
      run: |
        # On compile le fichier en restant à la racine du dépôt
        javac parser/ManifestParser.java
        
        # On l'exécute en indiquant la racine '.' comme Classpath (-cp) 
        # et en donnant le nom complet de la classe avec son package
        java -cp . parser.ManifestParser

    - name: Pousser la structure sur GitHub
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Ajoute l'arborescence générée par le script Java
        git add myfiles/
        
        # Le commit ne se fait que si Mojang a sorti une nouvelle version (différente de l'ancien index)
        if ! git diff-index --quiet HEAD; then
          git commit -m "🤖 Auto-update: Synchronisation complète des dossiers de téléchargement Mojang (avec client.txt)"
          git push
        else
          echo "Aucune modification détectée dans le manifeste de Mojang. Le site est déjà à jour."
        fi
